services:
  django_channels:
    container_name: django_channels
    image: django_channels_app:0.1
    build:
      context: ./core
    command: uvicorn core.asgi:application --host 0.0.0.0 --port 8000 --workers 4 --log-level debug --reload
    volumes:
      - ./core:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - celery
      - redis
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    restart: always
    container_name:  rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - .env
    # environment:
    #   - RABBITMQ_DEFAULT_USER="${RABBITMQ_DEFAULT_USER}"
    #   - RABBITMQ_DEFAULT_PASS="${RABBITMQ_DEFAULT_PASS}"

  redis:
    image: redis:7.2.4-alpine
    env_file:
      - .env
    ports:
      - 6379:6379
  
  redis_insight:
    image:  redislabs/redisinsight
    container_name: redis_insight
    ports:
      - '5541:5540'
    depends_on:
      - redis
      
  celery:
    container_name: celery
    build:
      context: ./core
    restart: always
    command: celery -A core worker --loglevel info -Q celery,celery:1,celery:2,celery:3
    volumes:
      - ./core:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis
      - rabbitmq
  
  # celery2:
  #   container_name: celery2
  #   build: 
  #     context: ./celeryworker
  #     dockerfile: Dockerfile
  #   restart: always
  #   command: celery -A celerytask worker -l info -Q queue2
  #   volumes:
  #     - ./celeryworker:/usr/src/app/
  #   depends_on:
  #     - redis
  #     - django_channels