# Generated by Django 5.0.6 on 2024-05-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodels',
            name='message',
            field=models.TextField(verbose_name='Notification'),
        ),
    ]
