# Generated by Django 5.0.6 on 2024-05-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationmodels_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationmodels',
            options={'verbose_name': 'Notification'},
        ),
        migrations.AlterField(
            model_name='notificationmodels',
            name='message',
            field=models.TextField(),
        ),
    ]
